apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://gitlab.cee.redhat.com/yuzheng/registry-proxy-test/deploy/base
# Enable this to create/rotate oauth secret
# - ../../oauth

images:
- name: quay.io/emilyzheng/image-rbac-proxy
  newName: quay.io/emilyzheng/image-rbac-proxy
  newTag: stage

configMapGenerator:
  - name: dex
    files:
      - dex-config.yaml

patches:
- path: configmap.yaml
- path: route-patch.yaml
  target:
    kind: Route
    group: route.openshift.io
    version: v1
- path: sa-patch.yaml
  target:
    kind: ServiceAccount
    name: dex-client
    version: v1
